### ISSUE TITLE
Add CMake configuration option to select Qt5 or Qt6

### ISSUE THREAD

**Issue by Flowdalic** [cvut/qtrvsim#144]
Gentoo downstream here.

It would be great if there was a CMake configuration option to select Qt5 or Qt6 (probably defaulting to autoselect). This makes it easier to reliable package qtrvsim [1]. Right now, qtrvsim basically establishes an automagic dependency on Qt, which is problematic [2].

1: https://bugs.gentoo.org/933594
2: https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies

**Comment by jdupak** [comment]
Hi Florian,
sure that should be very easy and I wanted to do it for development anyway.

I will get to it on Friday or during weekend.

It's there some established option name for this?

**Comment by Flowdalic** [comment]
I see
- `QT_VERSION_MAJOR`
- `QT_MAJOR_VERSION`
- `QTFIXEDVERSION`

being used in Gentoo. I would probably go with the first one, but no strong opinion. That said, options should be
- 5
- 6
- auto
with auto or 6 being the default.
