### ISSUE TITLE
Issues when packaging on Debian

### ISSUE THREAD

**Issue by yuzibo** [cvut/qtrvsim#149]
Hi,

I am packaging the qtrvsim to Debian. Everything is okay, but I got some hints from lintian's checking:

```
I: qtrvsim: desktop-entry-lacks-keywords-entry
[usr/share/applications/qtrvsim.desktop]
I: qtrvsim: spelling-error-in-binary Unknow Unknown [usr/bin/qtrvsim_cli]
I: qtrvsim: spelling-error-in-binary Unknow Unknown [usr/bin/qtrvsim_gui]

```
The first one I can patch this to fix it. But two later are minor I think also and it is worth to letting upstream know.

**Comment by ppisa** [comment]
The Keywords added in 0547088474de06e6b4680484c00058b8d4288b5d
I name of binary is unique and descriptive, so it is out of the spellchecker scope or spellchecker should learn it.

If there is no other suggestion, I will close issue before next release which is due soon.

**Comment by yuzibo** [comment]
Thanks for quickly response and fixing.

Okay, I have no other suggestion, so I can close the issue now.:)
