### ISSUE TITLE
SRA and SRAI are not arithmetic shifts

### ISSUE THREAD

**Issue by ekliptik** [cvut/qtrvsim#19]
Reproduce:
```
addi x10, x0, -3
addi x15, x0, 1
sra x12, x10, x15
```
```
addi x10, x0, -3
srai x12, x10, 0x1
```
Expected behavior:
content of x12 is -2 (0xfffffffe)
Actual behavior:
content of x12 is 0x7ffffffe
Version: 0.8.1

**Comment by ppisa** [comment]
Thanks updated and shift to 63 allowed for 64-bit mode. Word (32 bits) limited shift for 64-bit mode missing still.
