### ISSUE TITLE
pseudoinst_enabled not passed for --asm in CLI

### ISSUE THREAD

**Issue by strny0** [cvut/qtrvsim#36]
When running the cli with the following settings:
```bash
$ qtrvsim_cli --dump-cycles --asm --load-range 0x12340,array_size.in --load-range 0x12344,array_data.in --dump-range 0x12344,60,array_data.out bubble-sort.S
```
I get output:
```
[DEBUG] instruction:	Base instruction of the name la not found.
[DEBUG] instruction:	Base instruction of the name la not found.
[DEBUG] instruction:	Base instruction of the name bgt not found.
[DEBUG] instruction:	Base instruction of the name j not found.
[DEBUG] instruction:	Base instruction of the name j not found.
[DEBUG] machine.core:	Exception cause 9 instruction PC 0x0000025c next PC 0x00000260 jump branch PC 0x00000258 registers PC 0x00000260 mem ref 0x00000000
Machine stopped on BREAK exception.
Machine state report:
cycles: 784
stalls: 0
Failure closing array_data.out
```

Notably, I do not get these issues (with the instructions not found) when not using the `--asm` flag.
How come pesudo-instructions are not found with these settings?
Is it possible some bool value is not being passed down?

I was asking for support in the FEL Discord in `#apo` channel. Another user had the following idea:

`Instruction::pseudo_from_tokens` calls `code_from_tokens` always with `pseudoinst_enabled = false` because it does not accept `pseudoinst_enabled` as an argument. 

Can you confirm what happens what happens with the pseudoinst support if the `--asm` flag is used?

**Comment by ppisa** [comment]
Dear Jakub Strnad,

the message is of the DEBUG severity level. This means that only the Instruction::base_from_tokens() method reports that it does not recognize instruction but it is then processed by Instruction::pseudo_from_tokens() and whole Instruction::code_from_tokens() fills whole 8 byte buffer and reports 8 bytes size for the **la** instruction. So I expect that your code should be translated into memory correctly and is executed such as it is written. Check the behavior and if you find some problem report it.

We use the QtRVSim build for debugging mostly for now. But if it is build for release then the most of the non harm messages are suppressed. I have not check this actual one. CMake release build
```
cmake -DCMAKE_BUILD_TYPE=Release  ../qtrvsim-git
```
What is your QtRVSim binary from? Did you built it or it is from or laboratory server or some of the released packages?

Best wishes,

Pavel Pisa

**Comment by ppisa** [comment]
I have rebuild new version with new visualization on the Postel server in the Release build and DEBUG is suppressed and only reported message is
```
Machine stopped on BREAK exception.
```

**Comment by ppisa** [comment]
No confirmation of the correct behavior from issue author. My test showed no problem and reported output does not indicate any stop/exit of the program on error as well. The default build chnaged to Release in e5c60cce0b63bafc2a5b77cb87f9b2be998a9c88 to now mislead ordinary users with the information that given instruction cannot be parsed by Base instruction encoding function.
