### ISSUE TITLE
Fix Fedora (and Centos) OBS build

### ISSUE THREAD

**Issue by jdupak** [cvut/qtrvsim#4]
https://build.opensuse.org/package/live_build_log/home:jdupak/qtrvsim/Fedora_34/x86_64

**Comment by ppisa** [comment]
Fixed in b6a1ee8a97d0f69fd25e552dd50130b6364f01b7 Packaging: fix Fedora build.

We are thank Jan Grulich Jaroslav Reznik from Fedora project for their help with the problem solution.
