### ISSUE TITLE
can we switch to main branch?

### ISSUE THREAD

**Issue by okias** [cvut/qtrvsim#44]
Just because many project I'm currently contributing changed from the `master` to `main` branch, would it be option, as I know how much meaningless it is? What you think? (no feelings hurt if you don't want to :laughing: )

**Comment by ppisa** [comment]
Git still creates default branch as "master" and I do not like to break comparability. Default instructions on gitlab which mislead some of our students to manually rename master to main lead t not assigning them points etc... I do not expect that universities switch soon to Main Degree and mainers etc... On one side I understand to some arguments, but the price is too high, I am sure that bad matching to 50 years of communication standard terms would lead to mistakes and cause even death of people in the safety related areas. I consider this price too high.

**Comment by okias** [comment]
no, for me it's personally not about 'woke stuff', just for git it seems to be more... logic. Just since I'm doing CTRL-R in my `zsh`, I getting `git rebase -i devel/main` instead of `/master` these days. But I'm completly ok with keeping original git naming. Closing.

**Comment by jdupak** [comment]
> no, for me it's personally not about 'woke stuff', just for git it seems to be more... logic. Just since I'm doing CTRL-R in my `zsh`, I getting `git rebase -i devel/main` instead of `/master` these days. But I'm completly ok with keeping original git naming. Closing.

The situation is far from being that general. IIRC practically all projects I work with have `master`. + I am generally against that change.
