### ISSUE TITLE
Suspicious error when AT&T syntax is used

### ISSUE THREAD

**Issue by jdupak** [cvut/qtrvsim#51]
```
addi x1, x0, $5
addi x2, x1, $10
```
![image_2022-11-20_00-08-06](https://user-images.githubusercontent.com/22683640/202899312-2767abf1-755f-451d-9d2c-98618edcc9db.png)

Reported by @MatejKafka

**Comment by jdupak** [comment]
The syntax should not work, but the error seems fishy.

**Comment by ppisa** [comment]
Pull request with tested better solution is welcomed. Everybody can pour hands into it. Else, hopefully, it will be solved when you oe me find some time or will solve something else... By the way, caption hints like in RARS would be nice too, but I would make them with disable option. For skilled person can be distracting. So we are not short of ideas or work...
