### ISSUE TITLE
External Update of Value in CPU Address Space (e.g. from Peripherals) Does Update Memory Windows

### ISSUE THREAD

**Issue by ppisa** [cvut/qtrvsim#84]
How to reproduce, open Window Memory and Peripherals block. Enter address 0xffffc120 into Memory Widow location and turn the some of RGB knobs. The value on the address 0xffffc124 should update correspondingly. But it updates only when I click into memory window or step over memory load or store instruction.

The same problem is in UART when the character is entered into terminal input.

**Comment by jdupak** [comment]
Resolved with #85
