### ISSUE TITLE
Accept all argument formats

### ISSUE THREAD

**Issue by DoPri** [cvut/qtrvsim#86]
## Description
Accept all argument formats or at least those that [GAS](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=opcodes/riscv-opc.c;hb=HEAD) recognizes.

### Example
```
jalr x0, x0, 0
```
yields "number of arguments does not match", while
```
jalr x0, 0(x0)
```
gets accepted. See lines 374 and 375 [here](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=opcodes/riscv-opc.c;hb=HEAD#l374).

**Comment by ppisa** [comment]
Please recheck now. The mechanism to define instruction aliases has been introduced ace1abdcf331f3b9166cb262c5441e0a39c8146c  and should support much more jump instruction assembler level listing variants.
