### ISSUE TITLE
Is the number of sets limited same in web-version as the other version?

### ISSUE THREAD

**Issue by xmk1906** [cvut/qtrvsim#87]
In web version, I found the number of sets is 99 max ,it is same in the other version?

**Comment by jdupak** [comment]
It is limited everywhere (all platforms have the same configuration and differ only in platform limitation (filesystem access and process invocation in wasm)). The 99 limit seems to be a default by the QT UI. The simulatior itself has only implementation limits (like size of int used for indexing...).

So it can be easily changed. I have tested with 10k and it rusn smoothly, 1M get very slow to initialize (we have never cared for such numbers, so there might be a lot of place for optimization), but still runs OK.

Do you have any particular suggestion, what would be a reasonable maximum to use? I have to put there one, otherwise it defaults to 99.

**Comment by xmk1906** [comment]
> It is limited everywhere (all platforms have the same configuration and differ only in platform limitation (filesystem access and process invocation in wasm)). The 99 limit seems to be a default by the QT UI. The simulatior itself has only implementation limits (like size of int used for indexing...).
> 
> So it can be easily changed. I have tested with 10k and it rusn smoothly, 1M get very slow to initialize (we have never cared for such numbers, so there might be a lot of place for optimization), but still runs OK.
> 
> Do you have any particular suggestion, what would be a reasonable maximum to use? I have to put there one, otherwise it defaults to 99.

consider the possible situation,i think 10k is fine.

**Comment by xmk1906** [comment]
> It is limited everywhere (all platforms have the same configuration and differ only in platform limitation (filesystem access and process invocation in wasm)). The 99 limit seems to be a default by the QT UI. The simulatior itself has only implementation limits (like size of int used for indexing...).
> 
> So it can be easily changed. I have tested with 10k and it rusn smoothly, 1M get very slow to initialize (we have never cared for such numbers, so there might be a lot of place for optimization), but still runs OK.
> 
> Do you have any particular suggestion, what would be a reasonable maximum to use? I have to put there one, otherwise it defaults to 99.

Can I ask when the new version will be updated? No rush, meaning Excuse me.

**Comment by xmk1906** [comment]
> > > Do you have any particular suggestion, what would be a reasonable maximum to use? I have to put there one, otherwise it defaults to 99.
> > 
> > 
> > consider the possible situation,i think 10k is fine.
> 
> I am not sure if the size is not quite large for graphics drawing and even it would take considerable amount of memory. I have less fear for command line version when run as a native binary. But for graphics and even webassembly it is quite large. Simulator is not so fast anyway so it is questionable which task appropriate for QtRvSim needs such large cache. Cache principles are usually demonstrated on much smaller task where visualization is readable. For larger task, when only final statistic is importatnt there exists tools with better performance. Valgrind/cachegrind or simulators based on HDL simulation or specialized C/C++ architecture simulators which are closer to real systems. QtRvSim primary goal is visualization and demonstration for teaching not analytical tool for program profiling.
> 
> I am not fundamentally against something like 16384 sets max if it is checked that it would not block online and local graphic version considerably. But I would still like to discuss what will be benefit.
> 
> As for the next release, we have accumulated more changes in mainline and there are some waiting to be finished (interrupts support at least). There will be for sure one full release before next summer term of our course. It start in February. But there will be probably some earlier till the end of the year. Online version can be updated even earlier.

thank you for reponse,i think you are right,maybe 10k is too large,but i think the limmit 99 is too small.

**Comment by ppisa** [comment]
OK, I suggest 1024 as the limit in GUI version for now. CLI version can have different limit or be unlimited and it is responsibility of the user to be sane there.
